Repository poklist/poklist-frontend, pull requests merged in 2025-05, with the labels that each got.

#73 fix: enhance ImageCropper zoom handling and slider integration
  src/components/ImageCropper/index.tsx
  src/components/ui/slider.tsx
Labels: bug

#74 fix: safari textarea line clamping issue
  src/pages/Idea/Components/Form/index.tsx
  src/pages/Lists/Components/Form/index.tsx
Labels: bug

#75 fix: change list/idea cover img, username validate timing, preload homepage img
  src/components/FakePage/EditFieldFakePage.tsx
  src/pages/Home/Components/FeatureSection/index.tsx
  src/pages/Idea/Components/DeleteButton/index.tsx
  src/pages/Idea/Components/Form/index.tsx
  src/pages/Lists/Components/Form/index.tsx
Labels: bug, FE

#78 feat: create login drawer component
  src/components/Drawer/LoginDrawer.tsx
Labels: enhancement

#80 feat: discovery page
  src/assets/images/officialCover/random-image-1.png
  src/assets/images/officialCover/random-image-2.png
  src/assets/images/officialCover/random-image-3.png
  src/assets/images/officialCover/random-image-4.png
  src/components/Drawer/index.tsx
  src/components/Header/BackToUserHeader.tsx
  src/components/Header/index.tsx
  src/hooks/mutations/useEditProfile.ts
  src/hooks/queries/useLatestListGroups.ts
  src/hooks/queries/useOfficialCollections.ts
  src/hooks/useCheckStorage.ts
  src/hooks/useScrollPosition.ts
  src/hooks/useStrictNavigate.ts
  src/locales/en/messages.po
  src/locales/zh-TW/messages.po
  src/pages/Discovery/Components/FooterSection/index.tsx
  src/pages/Discovery/Components/HeaderSection/index.tsx
  src/pages/Discovery/Components/ListItem/ListItemSkeleton.tsx
  src/pages/Discovery/Components/ListItem/index.tsx
  src/pages/Discovery/Components/ListSection/ListSectionSkeleton.tsx
  src/pages/Discovery/Components/ListSection/README.md
  src/pages/Discovery/Components/ListSection/index.tsx
  src/pages/Discovery/Components/SectionTitle/SectionTitleSkeleton.tsx
  src/pages/Discovery/Components/SectionTitle/index.tsx
  src/pages/Discovery/Components/TileList/TileListSkeleton.tsx
  src/pages/Discovery/Components/TileList/index.tsx
  src/pages/Discovery/Components/TileSection/TileSectionSkeleton.tsx
  src/pages/Discovery/Components/TileSection/index.tsx
  src/pages/Discovery/index.tsx
  src/pages/Home/index.tsx
  src/pages/Layout/Components/MainContent.tsx
  src/pages/Layout/index.tsx
  src/pages/Settings/BlocksSection/index.tsx
  src/pages/Settings/index.tsx
  src/pages/User/HeroSection/index.tsx
  src/router/index.tsx
  src/stores/useUIStore.ts
  src/types/Discovery/index.ts
  src/types/Home/index.ts
Labels: documentation, enhancement
