Repository poklist/poklist-frontend, pull requests merged in 2025-01, with the labels that each got.

#32 ci: netlify dev
  netlify.toml
  package.json
  vite.config.ts
Labels: help wanted, FE

#37 feature: edit list
  src/components/Radio/index.tsx
  src/components/ui/button.tsx
  src/components/ui/drawer.tsx
  src/hooks/Ideas/useCreateIdea.ts
  src/hooks/Lists/useCreateList.ts
  src/hooks/Lists/useDeleteList.ts
  src/hooks/Lists/useEditList.ts
  src/hooks/Lists/useGetList.ts
  src/lib/axios.ts
  src/lib/utils.ts
  src/locales/en/messages.po
  src/locales/en/messages.ts
  src/locales/zh-TW/messages.po
  src/locales/zh-TW/messages.ts
  src/pages/Lists/Create/index.tsx
  src/pages/Lists/Edit/DeleteButton/index.tsx
  src/pages/Lists/Edit/Form/index.tsx
  src/pages/Lists/Edit/Header/index.tsx
  src/pages/Lists/Edit/i18n.ts
  src/pages/Lists/Edit/index.tsx
  src/pages/Lists/Manage/index.tsx
  src/router/index.tsx
Labels: FE

#35 refactor: Home page
  src/assets/images/logo-big.svg
  src/assets/images/mascot/mascot-big.png
  src/assets/images/mascot/mascot-big.svg
  src/assets/images/mascot/mascot-small.png
  src/assets/images/mascot/mascot-small.svg
  src/assets/images/socialMedia/instgram-logo.svg
  src/assets/images/socialMedia/threads-logo.svg
  src/components/Home/Divider.tsx
  src/components/Home/Footer.tsx
  src/components/Home/Header.tsx
  src/components/Home/HeroSection.tsx
  src/components/Home/InfoSection.tsx
  src/components/Home/Tutorial.tsx
  src/constants/home.ts
  src/pages/Home/OldHeroSection.tsx
  src/pages/Home/index.tsx
  src/pages/Settings/BlocksSection/index.tsx
  src/router/index.tsx
  tailwind.config.js
Labels: enhancement, FE

#38 feat: Add error page
  src/pages/Error/index.tsx
  src/router/index.tsx
Labels: enhancement, FE
